---
title: "hmda_maps"
output: html_document
date: "2024-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(choroplethr)
library(choroplethrMaps)
library(choroplethrZip)
```

## Second Homes
```{r}
map_tracts<-function(data,state,title)
{
  library(ggplot2)
  library(RColorBrewer)
  cap_state<-gsub("(^|[[:space:]])([[:alpha:]])", "\\1\\U\\2",    # Uppercase with Base R
     state,
     perl = TRUE)
  map_title<-paste(cap_state,title)
  return (invisible(
    tract_choropleth(data,state_name=state,title=map_title)
    +
      scale_fill_manual(values=c("<1%" = "#ffffffff",  
                             "%1-5%" = "#64acbe", 
                             "5-10%" = "#c85a5a", 
                             ">10%" = "#574249"),
                    name="Second Homes")
    ))
}
```

```{r}
setwd('/home/shino/00 SF Loan Performance/00nano/89hmda')
outfile<-'second.tsv'
overwrite<-FALSE
if(overwrite | !file.exists(outfile))
{
  system('cat second_hmda_v01.sql | time mysql --login-path=shino loans | tee second.tsv')
}
data<-read.csv(outfile,sep='\t') ## ,colClasses=c("character","numeric"))

data[data$value>0.10,2]=">10%"
data[data$value>0.05,2]="5-10%"
data[data$value>0.01,2]="1-5%"
data[data$value<=0.01,2]="<1%"


#ny<-invisible(tract_choropleth(data,"new york"))
#nj<-tract_choropleth(data,"new jersey")
map_title<-"Conventional Mortgage Second Homes in 2022"
maps<-list()
data(state.regions)
```

```{r map,message=FALSE,warning=FALSE,include=FALSE}
setwd('/home/shino/00 SF Loan Performance/00nano/89hmda')
outfile<-'second.tsv'
overwrite<-FALSE
if(overwrite | !file.exists(outfile))
{
  system('cat second_hmda_v01.sql | time mysql --login-path=shino loans | tee second.tsv')
}
data<-read.csv(outfile,sep='\t') ## ,colClasses=c("character","numeric"))
data[data$value>0.10,2]=">10%"
data[data$value>0.05,2]="5-10%"
data[data$value>0.01,2]="1-5%"
data[data$value<=0.01,2]="<1%"

#ny<-invisible(tract_choropleth(data,"new york"))
#nj<-tract_choropleth(data,"new jersey")
map_title<-"Conventional Mortgage Second Homes in 2022"
maps<-list()
data(state.regions)

for (state_name in c('new york','new jersey','california','texas')) # state.regions[,1])
{
  maps<-append(maps,list(map_tracts(data,state_name,map_title)))
}
```

```{r}
for (map in maps)
{
  print(map)
}

```

